apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "web-manager.labels" . | indent 4 }}
  name: properties
data:
  sys.properties:
{{- with .Values.sys.data }}
   {{ toYaml . | indent 4 }}
{{- end }}
  jdbc.properties:
{{- with .Values.jdbc.data }}
   {{ toYaml . | indent 4 }}
{{- end }}
